/**
 * Course notes, as a downloadable Markdown file.
 *
 * Built entirely in the browser from data the dashboard already holds, so
 * downloading notes costs no round trip, no server-side rendering and no
 * new endpoint. The syllabus is in `CourseInfo.modules` — the same list the
 * course-detail dialog walks — so the file cannot drift from what the student
 * was shown.
 *
 * Markdown rather than PDF: it is plain text, it opens in every editor and
 * notes app, and it is searchable. Generating a PDF in the browser means
 * shipping a renderer for a document nobody asked to be pixel-perfect, and the
 * student wants something to revise from, not something to admire.
 *
 * Progress is included because "which modules have I actually finished" is the
 * first question a student asks of their own notes, and answering it here saves
 * them cross-referencing the dashboard.
 */

export interface NotesCourse {
  title: string;
  category: string;
  description: string;
  level: string;
  modules: Array<{ title: string; topic: string; subtopics?: string[] }>;
}

/** Filename-safe slug, so a download never lands as `concepts?.md`. */
export function slugify(value: string): string {
  return (
    value
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, "-")
      .replace(/^-+|-+$/g, "")
      .slice(0, 60) || "course"
  );
}

/**
 * Render a course as Markdown.
 *
 * Deliberately plain: headings, bullets and a progress marker. Anything richer
 * (tables, callouts) is harder to read in a notes app than in a preview.
 */
export function buildCourseNotes(
  course: NotesCourse,
  completedModules: string[] = [],
  language: "en" | "hi" = "en",
): string {
  const done = new Set(completedModules);
  const copy =
    language === "hi"
      ? {
          heading: "AgentEd — कोर्स नोट्स",
          level: "स्तर",
          category: "श्रेणी",
          overview: "अवलोकन",
          modules: "मॉड्यूल",
          subtopics: "विषय-वस्तु",
          progress: "प्रगति",
          doneMark: "पूर्ण",
          pendingMark: "बाकी",
          summary: "सारांश",
          emptyNotes: "इस मॉड्यूल के लिए अभी विषय-वस्तु नहीं लिखी गई है।",
          footer: "यह नोट्स AgentEd से स्वतः बनाए गए हैं।",
        }
      : {
          heading: "AgentEd — Course Notes",
          level: "Level",
          category: "Category",
          overview: "Overview",
          modules: "Modules",
          subtopics: "Topics covered",
          progress: "Progress",
          doneMark: "Done",
          pendingMark: "Not started",
          summary: "Summary",
          emptyNotes: "No subtopics have been written for this module yet.",
          footer: "Generated by AgentEd.",
        };

  const lines: string[] = [];

  lines.push(`# ${course.title}`, "");
  // The product line carries the translation, because the course title itself is
  // the syllabus's own wording and is deliberately left alone — translating a
  // module name the tutor will never say in Hindi would just invent a second
  // vocabulary for the same concept.
  lines.push(`_${copy.heading}_`, "");
  lines.push(`**${copy.level}:** ${course.level}  `);
  lines.push(`**${copy.category}:** ${course.category}`, "");
  lines.push(`## ${copy.overview}`, "", course.description, "");
  lines.push(`## ${copy.modules}`, "");

  course.modules.forEach((module, index) => {
    const isDone = done.has(module.title);
    const mark = isDone ? `✅ ${copy.doneMark}` : `⬜ ${copy.pendingMark}`;
    lines.push(`### ${index + 1}. ${module.title} — ${mark}`, "");
    lines.push(`*Topic: ${module.topic}*`, "");

    const subtopics = (module.subtopics ?? []).filter((sub) => sub.trim());
    if (subtopics.length) {
      lines.push(`**${copy.subtopics}:**`, "");
      for (const sub of subtopics) {
        lines.push(`- ${sub.trim()}`);
      }
      lines.push("");
    } else {
      lines.push(copy.emptyNotes, "");
    }
  });

  const finished = course.modules.filter((m) => done.has(m.title)).length;
  const percent = course.modules.length
    ? Math.round((finished / course.modules.length) * 100)
    : 0;

  lines.push("---", "", `## ${copy.summary}`, "");
  lines.push(`- **${copy.progress}:** ${finished}/${course.modules.length} modules (${percent}%)`);
  lines.push(`- **${copy.modules}:** ${course.modules.length}`);
  lines.push(`- **Exported:** ${new Date().toISOString().slice(0, 10)}`, "");
  lines.push(`_${copy.footer}_`, "");

  return lines.join("\n");
}

/**
 * Hand the browser a download of `content`.
 *
 * Object URLs are revoked on the next tick rather than left to the collector: a
 * long session taking notes on several courses would otherwise hold every one of
 * them in memory for the life of the page.
 */
export function downloadTextFile(
  filename: string,
  content: string,
  mimeType = "text/markdown;charset=utf-8",
): void {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const anchor = document.createElement("a");
  anchor.href = url;
  anchor.download = filename;
  anchor.rel = "noopener";
  document.body.append(anchor);
  anchor.click();
  anchor.remove();
  window.setTimeout(() => URL.revokeObjectURL(url), 0);
}